### ISSUE TITLE
Database relation infinite loop

### ISSUE THREAD

**Issue by iron2414** [micronaut-projects/micronaut-serialization#226]
### Expected Behavior

When having a Many-to-one (vote) One-to-many (answer) relationship, and if I query all the votes ( `voteRepository.findAll()`) with leftJoin, then I'd expect each vote once, with an array of answers. And each answer has either `null` value as a vote.

And if I query an answer, I'd expect the same behaviour, it has 1 vote, and the vote has `null` as answers.
Code:
```
@MappedEntity("vote")
@Serdeable
public class Vote {
       @Id
       @GeneratedValue
	private Integer id;
	// ...

    @Relation(value = Relation.Kind.ONE_TO_MANY, mappedBy = "vote")
    private Set<Answer> answers;
}
```

```
@MappedEntity("answer")
@Serdeable
public class Answer {
       @Id
       @GeneratedValue
	private Integer id;
	// ...

    @Relation(value = Relation.Kind.MANY_TO_ONE)
    // @JsonIgnore  <- if this is not here, it gives infinite error
    private Vote vote;
}
```

```
@JdbcRepository(dialect = POSTGRES)
public interface VoteRepository extends CrudRepository<Vote, Integer> {

    @Join(value = "answers", type = Join.Type.LEFT_FETCH)
    List<Vote> findAll();
}
```

### Actual Behaviour

When calling `voteRepository.findAll()` I get the following exception: 

```
	Suppressed: java.lang.IllegalStateException: There is still an unfinished child generator
		at io.micronaut.serde.jackson.SpecializedJacksonEncoder.checkChild(SpecializedJacksonEncoder.java:53)
		at io.micronaut.serde.jackson.SpecializedJacksonEncoder.finishStructure(SpecializedJacksonEncoder.java:90)
		at io.micronaut.serde.jackson.SpecializedJacksonEncoder.close(SpecializedJacksonEncoder.java:99)
		at io.micronaut.serde.support.serializers.CustomizedIterableSerializer.serialize(CustomizedIterableSerializer.java:53)
		at io.micronaut.serde.support.serializers.CustomizedIterableSerializer.serialize(CustomizedIterableSerializer.java:32)
		at io.micronaut.serde.support.serializers.CustomizedObjectSerializer.serialize(CustomizedObjectSerializer.java:123)
		at io.micronaut.serde.support.serializers.CustomizedObjectSerializer.serialize(CustomizedObjectSerializer.java:123)
		at io.micronaut.serde.support.serializers.CustomizedIterableSerializer.serialize(CustomizedIterableSerializer.java:50)
		at io.micronaut.serde.support.serializers.CustomizedIterableSerializer.serialize(CustomizedIterableSerializer.java:32)
		at io.micronaut.serde.support.serializers.CustomizedObjectSerializer.serialize(CustomizedObjectSerializer.java:123)
		at io.micronaut.serde.support.serializers.CustomizedObjectSerializer.serialize(CustomizedObjectSerializer.java:123)
		at io.micronaut.serde.support.serializers.CustomizedIterableSerializer.serialize(CustomizedIterableSerializer.java:50)
		at io.micronaut.serde.support.serializers.CustomizedIterableSerializer.serialize(CustomizedIterableSerializer.java:32)
		at io.micronaut.serde.support.serializers.CustomizedObjectSerializer.serialize(CustomizedObjectSerializer.java:123)
		at io.micronaut.serde.support.serializers.CustomizedObjectSerializer.serialize(CustomizedObjectSerializer.java:123)
		at io.micronaut.serde.support.serializers.CustomizedIterableSerializer.serialize(CustomizedIterableSerializer.java:50)
		at io.micronaut.serde.support.serializers.CustomizedIterableSerializer.serialize(CustomizedIterableSerializer.java:32)
		at io.micronaut.serde.support.serializers.CustomizedObjectSerializer.serialize(CustomizedObjectSerializer.java:123)
		at io.micronaut.serde.support.serializers.CustomizedObjectSerializer.serialize(CustomizedObjectSerializer.java:123)
		at io.micronaut.serde.support.serializers.CustomizedIterableSerializer.serialize(CustomizedIterableSerializer.java:50)
		at io.micronaut.serde.support.serializers.CustomizedIterableSerializer.serialize(CustomizedIterableSerializer.java:32)
		at io.micronaut.serde.support.serializers.CustomizedObjectSerializer.serialize(CustomizedObjectSerializer.java:123)
		at io.micronaut.serde.support.serializers.CustomizedObjectSerializer.serialize(CustomizedObjectSerializer.java:123)
		at io.micronaut.serde.support.serializers.CustomizedIterableSerializer.serialize(CustomizedIterableSerializer.java:50)
		at io.micronaut.serde.support.serializers.CustomizedIterableSerializer.serialize(CustomizedIterableSerializer.java:32)
		at io.micronaut.serde.support.serializers.CustomizedObjectSerializer.serialize(CustomizedObjectSerializer.java:123)
		at io.micronaut.serde.support.serializers.CustomizedObjectSerializer.serialize(CustomizedObjectSerializer.java:123)
		.....
```
Which repeats until the stack is full.

If I add the `@JsonIgnore` to the Answer entity, then it loads correctly. However I can't query an Answer with it's vote anymore.

### Steps To Reproduce

pom.xml: 

```
  <dependencies>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-inject</artifactId>
      <scope>compile</scope>
      <version>3.4.4</version>
    </dependency>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-validation</artifactId>
      <scope>compile</scope>
      <version>3.4.4</version>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
      <version>5.9.0-M1</version>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <scope>test</scope>
      <version>5.9.0-M1</version>
    </dependency>
    <dependency>
      <groupId>io.micronaut.test</groupId>
      <artifactId>micronaut-test-junit5</artifactId>
      <scope>test</scope>
      <version>3.3.0</version>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <scope>test</scope>
      <version>4.6.0</version>
    </dependency>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-http-client</artifactId>
      <scope>compile</scope>
      <version>3.4.4</version>
    </dependency>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-http-server-netty</artifactId>
      <scope>compile</scope>
      <version>3.4.4</version>
    </dependency>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-management</artifactId>
      <scope>compile</scope>
      <version>3.4.4</version>
    </dependency>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-jackson-databind</artifactId>
      <scope>compile</scope>
      <version>3.4.4</version>
    </dependency>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-runtime</artifactId>
      <scope>compile</scope>
      <version>3.4.4</version>
    </dependency>
    <dependency>
      <groupId>io.micronaut.data</groupId>
      <artifactId>micronaut-data-jdbc</artifactId>
      <scope>compile</scope>
      <version>3.4.1</version>
    </dependency>
    <dependency>
      <groupId>io.micronaut.flyway</groupId>
      <artifactId>micronaut-flyway</artifactId>
      <scope>compile</scope>
      <version>5.3.0</version>
    </dependency>
    <dependency>
      <groupId>io.micronaut.security</groupId>
      <artifactId>micronaut-security</artifactId>
      <scope>compile</scope>
      <version>3.6.0</version>
    </dependency>
    <dependency>
      <groupId>io.micronaut.security</groupId>
      <artifactId>micronaut-security-jwt</artifactId>
      <scope>compile</scope>
      <version>3.6.0</version>
    </dependency>
    <dependency>
      <groupId>io.micronaut.security</groupId>
      <artifactId>micronaut-security-oauth2</artifactId>
      <scope>compile</scope>
      <version>3.6.0</version>
    </dependency>
    <dependency>
      <groupId>io.micronaut.serde</groupId>
      <artifactId>micronaut-serde-jackson</artifactId>
      <scope>compile</scope>
      <version>1.1.0</version>
    </dependency>
    <dependency>
      <groupId>io.micronaut.sql</groupId>
      <artifactId>micronaut-jdbc-hikari</artifactId>
      <scope>compile</scope>
      <version>4.4.0</version>
    </dependency>
    <dependency>
      <groupId>io.swagger.core.v3</groupId>
      <artifactId>swagger-annotations</artifactId>
      <scope>compile</scope>
      <version>2.2.0</version>
    </dependency>
    <dependency>
      <groupId>jakarta.annotation</groupId>
      <artifactId>jakarta.annotation-api</artifactId>
      <scope>compile</scope>
      <version>2.1.0</version>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <scope>runtime</scope>
      <version>1.2.11</version>
    </dependency>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <version>42.3.6</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
      <version>1.18.24</version>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
      <version>1.17.2</version>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>postgresql</artifactId>
      <scope>test</scope>
      <version>1.17.2</version>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>testcontainers</artifactId>
      <scope>test</scope>
      <version>1.17.2</version>
    </dependency>
  </dependencies>
 ```

### Environment Information

- Opearting System: MacOS, Win10
- SDK: OpenJDK17

### Version

3.4.2

**Comment by graemerocher** [comment]
You can use managed references similar to Jackson https://stackoverflow.com/questions/29177794/jackson-circular-dependencies

Have you tried this?

**Comment by iron2414** [comment]
I just did, but it not compiles (`Back reference declares an inverse property [answers] that doesn't exist in type')

**Comment by graemerocher** [comment]
please upload an example application to github
