### ISSUE TITLE
Library not working without micronaut-runtime module

### ISSUE THREAD

**Issue by Happy-Neko** [micronaut-projects/micronaut-serialization#228]
### Expected Behavior

One should be able to inject `ObjectMapper` if micronaut is used as IoC container only.

### Actual Behaviour

Application fails `ObjectMapper` bean injection with exception.
```
Exception in thread "main" io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.serde.jackson.JacksonJsonMapper]

Message: Error loading bean [io.micronaut.serde.support.serdes.HealthStatusSerde]: io/micronaut/health/HealthStatus
Path Taken: new JacksonJsonMapper(SerdeRegistry registry) --> new JacksonJsonMapper([SerdeRegistry registry])
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2344)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2282)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2228)
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:2989)
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2891)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2852)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2773)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1594)
        at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66)
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2055)
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1285)
        at io.micronaut.serde.jackson.$JacksonJsonMapper$Definition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2331)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2282)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2228)
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:2989)
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2891)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2852)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2773)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1594)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:863)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:855)
        at com.example.Application.main(Application.java:47)
Caused by: io.micronaut.context.exceptions.BeanContextException: Error loading bean [io.micronaut.serde.support.serdes.HealthStatusSerde]: io/micronaut/health/HealthStatus
        at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:2073)
        at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:256)
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:3066)
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:3031)
        at io.micronaut.context.DefaultBeanContext.findBeanDefinition(DefaultBeanContext.java:784)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2763)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1594)
        at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66)
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2055)
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1285)
        at io.micronaut.serde.support.$DefaultSerdeRegistry$Definition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2331)
        ... 24 more
Caused by: java.lang.NoClassDefFoundError: io/micronaut/health/HealthStatus
        at io.micronaut.serde.support.serdes.$HealthStatusSerde$Definition.<clinit>(Unknown Source)
        at io.micronaut.serde.support.serdes.$HealthStatusSerde$Definition$Reference.load(Unknown Source)
        at io.micronaut.context.AbstractInitializableBeanDefinitionReference.load(AbstractInitializableBeanDefinitionReference.java:145)
        at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:2071)
        ... 35 more
Caused by: java.lang.ClassNotFoundException: io.micronaut.health.HealthStatus
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 39 more
```

### Steps To Reproduce

1. Create minimal app with Micronaut IoC and Micronaut Serialization.
```
plugins {
    id("io.micronaut.minimal.application").version("3.4.1")
    application
}

application {
    mainClass.set("com.example.Application")
}

micronaut {
    version.set("3.5.1")
}

dependencies {
    annotationProcessor(group = "io.micronaut.serde", name = "micronaut-serde-processor", version = "1.1.0")
    implementation(group = "io.micronaut.serde", name = "micronaut-serde-jackson", version = "1.1.0")
}
```
2. Try to inject ObjectMapper from application context.
```
context.getBean(ObjectMapper.class);
```

### Version

serde 1.1.0

**Comment by sdelamo** [comment]
I am not able to verify it: 

Create an application with `serialization-jackson` feautre: 

https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_11&lang=JAVA&build=GRADLE&test=JUNIT&features=serialization-jackson&version=3.6.0

Create a controlller: 

```java
package com.example;

import io.micronaut.context.BeanContext;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import io.micronaut.serde.ObjectMapper;

@Controller
public class HomeController {

    private final BeanContext context;

    public HomeController(BeanContext context) {
        this.context = context;
    }

    @Get
    String index() {
        return "Hello World is" + context.containsBean(ObjectMapper.class);
    }
}

```

Create a test: 

```java
package com.example;

import io.micronaut.context.BeanContext;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import io.micronaut.serde.ObjectMapper;

@Controller
public class HomeController {

    private final BeanContext context;

    public HomeController(BeanContext context) {
        this.context = context;
    }

    @Get
    String index() {
        return "Hello World is " + context.containsBean(ObjectMapper.class);
    }
}
```

It works fine.
