### ISSUE TITLE
JsonTypeInfo defaultImpl doesn't seem to work in Kotlin

### ISSUE THREAD

**Issue by dobbysock1002** [micronaut-projects/micronaut-serialization#318]
### Expected Behavior

I've created an abstract class with two child classes. I used the JsonTypeInfo annotation on the abstract class and marked one of the classes as the default implementation as shown below. When the type identifier `animalType` can't be mapped to a known subtype (in this case, is anything other than "dog"), I would expect the default class (`Cat`) to be used for deserialization.

```
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.PROPERTY,
        property = "animalType",
        defaultImpl = Cat::class
)
@JsonSubTypes(JsonSubTypes.Type(value = Dog::class, name = "dog"))
@Serdeable
abstract class Animal(
    open val field1: String,
    open val field2: Any,
)

@JsonTypeName("dog")
@Serdeable
data class Dog (
    override val field1: String,
    override val field2: String
): Animal(field1, field2)

@Serdeable
data class Cat (
    override val field1: String,
    override val field2: Number
): Animal(field1, field2)
```

### Actual Behaviour

An error occurs:

```
com.example.Animal
java.lang.InstantiationError: com.example.Animal
	at com.example.$Animal$Introspection.instantiateInternal(Unknown Source)
	at io.micronaut.inject.beans.AbstractInitializableBeanIntrospection.instantiate(AbstractInitializableBeanIntrospection.java:234)
	at io.micronaut.core.beans.BeanIntrospection.instantiate(BeanIntrospection.java:81)
	at io.micronaut.serde.support.deserializers.SpecificObjectDeserializer.deserialize(SpecificObjectDeserializer.java:277)
	at io.micronaut.serde.jackson.JacksonJsonMapper.readValue0(JacksonJsonMapper.java:131)
	at io.micronaut.serde.jackson.JacksonJsonMapper.readValue(JacksonJsonMapper.java:116)
	at io.micronaut.serde.jackson.JacksonJsonMapper.readValue(JacksonJsonMapper.java:167)
	at io.micronaut.json.JsonMapper.readValue(JsonMapper.java:97)
	at io.micronaut.serde.ObjectMapper.readValue(ObjectMapper.java:72)
	at com.example.AnimalTest.testUnexpectedSubType(AnimalTest.kt:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	...
```

### Steps To Reproduce

1. Create an abstract Kotlin class
2. Create two child classes of the abstract class
3. Annotate the abstract class with the following JsonTypeInfo annotation
`@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "<insert property here>", defaultImpl = <insert class here>::class)`
4. Attempt to deserialize using ObjectMapper with the type identifier field set to an unknown subtype.

### Environment Information

os: macOs currrent
jdk: 11

### Example Application

https://github.com/dobbysock1002/simple_debug_default_jsonsubtype

### Version

application version 3.6.3, serde version 1.3.3

**Comment by graemerocher** [comment]
As a workaround can you try add `@DefaultImplementation(Cat::class)`

**Comment by dobbysock1002** [comment]
I tried adding that above the abstract class but I get the same error. From the docs it sounds like that annotation might only be applicable to interfaces.

**Comment by graemerocher** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-serialization/commit/5b3f3f6306c503203251afdd9f82b796eb232868
