### ISSUE TITLE
Micronaut ignoring ObjectMapper configuration!

### ISSUE THREAD

**Issue by averri** [micronaut-projects/micronaut-serialization#394]
### Expected Behavior

I expect Micronaut to use the provided `ObjectMapper` for serialization.

### Actual Behaviour

Micronaut completely ignores the configured `ObjectMapper` and fails to serialize data.

### Steps To Reproduce

Use the following code to reproduce.

External dependencies for Java Money and the Jackson serialization module:

```kotlin
    implementation("org.javamoney:moneta:1.4.2")
    implementation("org.zalando:jackson-datatype-money:1.3.0")
```

The controller:

```kotlin
import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Get
import io.micronaut.security.annotation.Secured
import io.micronaut.security.rules.SecurityRule
import io.micronaut.serde.annotation.Serdeable
import org.javamoney.moneta.Money
import javax.money.MonetaryAmount


@Serdeable
class Item(
    var name: String = "",
    var price: MonetaryAmount = Money.of(0, "USD")
)


@Controller("/items")
@Secured(SecurityRule.IS_ANONYMOUS)
class ItemController {

    @Get
    fun get(): List<Item> {
        return listOf(
            Item("laptop", Money.of(800, "USD"))
        )
    }

}
```

The listener to configure `ObjectMapper`:

```kotlin
import com.fasterxml.jackson.databind.ObjectMapper
import io.micronaut.context.event.BeanCreatedEvent
import io.micronaut.context.event.BeanCreatedEventListener
import jakarta.inject.Singleton
import org.zalando.jackson.datatype.money.MoneyModule


@Singleton
class ObjectMapperBeanEventListener : BeanCreatedEventListener<ObjectMapper> {

    override fun onCreated(event: BeanCreatedEvent<ObjectMapper>): ObjectMapper {
        return event.bean.registerModule(MoneyModule())
    }
}
```

Invoking the endpoint with `GET http://localhost:5000/items` return an error:

```
Caused by: io.micronaut.core.beans.exceptions.IntrospectionException: No serializable introspection present for type Money. Consider adding Serdeable. Serializable annotate to type Money. Alternatively if you are not in control of the project's source code, you can use @SerdeImport(Money.class) to enable serialization of this type.
	at io.micronaut.serde.support.DefaultSerdeIntrospections.getSerializableIntrospection(DefaultSerdeIntrospections.java:101)
	at io.micronaut.serde.support.serializers.SerBean.<init>(SerBean.java:101)
	at io.micronaut.serde.support.serializers.ObjectSerializer.create(ObjectSerializer.java:193)
	at io.micronaut.serde.support.serializers.ObjectSerializer.lambda$getSerBean$0(ObjectSerializer.java:184)
	at io.micronaut.core.util.SupplierUtil$1.initialize(SupplierUtil.java:48)
	at io.micronaut.core.util.SupplierUtil$1.get(SupplierUtil.java:43)
	at io.micronaut.serde.support.serializers.ObjectSerializer.createSpecific(ObjectSerializer.java:83)
	at io.micronaut.serde.support.serializers.ObjectSerializer$RuntimeTypeSerializer.tryToFindSerializer(ObjectSerializer.java:280)
	at io.micronaut.serde.support.serializers.ObjectSerializer$4.tryToFindSerializer(ObjectSerializer.java:207)
	at io.micronaut.serde.support.serializers.ObjectSerializer$RuntimeTypeSerializer.lambda$getSerializer$0(ObjectSerializer.java:264)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at io.micronaut.serde.support.serializers.ObjectSerializer$RuntimeTypeSerializer.getSerializer(ObjectSerializer.java:262)
	at io.micronaut.serde.support.serializers.ObjectSerializer$RuntimeTypeSerializer.isEmpty(ObjectSerializer.java:240)
	at io.micronaut.serde.support.serializers.CustomizedObjectSerializer.serialize(CustomizedObjectSerializer.java:94)
	... 331 common frames omitted
```

Why Micronaut is not using the provided `ObjectMapper`?

If I use the instance of the provided `ObjectMapper` directly, it works with no issues.

Running: 

```kotlin
val objectMapper = ObjectMapper()
objectMapper.registerModule(MoneyModule())
println(objectMapper.writeValueAsString(Item("laptop")))
```
... returns correctly:

```
{"name":"laptop","price":{"amount":0.00,"currency":"USD"}}
```

### Environment Information

- Windows 11
- Java:
```
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)
```

### Version

3.8.6

**Comment by graemerocher** [comment]
you are trying to use a Jackson module. Micronaut Serialization doesn't support Jackson module's. If you want to use Jackson then use `micronaut-jackson-databind` dependency instead.

**Comment by averri** [comment]
Hi @graemerocher, thank you so much for that information, I was confused by the Micronaut Serialization documentation, where it shows a test using `ObjectMapper` together with an instance of a class annotated with `Serdeable`. 

I have a project already using `ObjectMapper`, so I wanted to reuse it to avoid code duplication. But another better option would be to use only Micronaut Serialization, which is a great option because it does not use reflection and has a better runtime footprint.

**Question**: Is it possible to use Micronaut Serialization outside of the Micronaut application context? If yes, I will modify other parts of the code and get rid of Jackson entirely.

**Comment by yawkat** [comment]
it is a bit confusing because serde also has a class called ObjectMapper, but it's not the jackson class of the same name.

You can use serde outside an application context, using JsonMapper.createDefault. however this will be limited (e.g. wont load any serializers you defined) so it's recommended to try to get the app context everywhere.
