### ISSUE TITLE
SerdeImport doesn't seem to be working with MicroStream and M5

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-serialization#450]
We use `@SerdeImport` in the microstream module to allow serialization of MicroStream classes

https://github.com/micronaut-projects/micronaut-microstream/blob/aaf2c6ce2cfe4121c7081d42ec385c293a5c09ab/microstream-rest/src/main/java/io/micronaut/microstream/rest/MicroStreamRestController.java#L43-L46

We updated to M3 of micronaut and M5 of serialization, and we're now seeing failures:

```
Caused by: io.micronaut.core.beans.exceptions.IntrospectionException: No serializable introspection present for type ViewerStorageFileStatistics. Consider adding Serdeable. Serializable annotate to type ViewerStorageFileStatistics. Alternatively if you are not in control of the project's source code, you can use @SerdeImport(ViewerStorageFileStatistics.class) to enable serialization of this type.
        at io.micronaut.serde.support.DefaultSerdeIntrospections.getSerializableIntrospection(DefaultSerdeIntrospections.java:102)
        at io.micronaut.serde.support.serializers.SerBean.<init>(SerBean.java:107)
        at io.micronaut.serde.support.serializers.ObjectSerializer.create(ObjectSerializer.java:212)
        at io.micronaut.serde.support.serializers.ObjectSerializer.lambda$getSerBean$0(ObjectSerializer.java:206)
        at io.micronaut.core.util.SupplierUtil$1.get(SupplierUtil.java:47)
        at io.micronaut.serde.support.serializers.ObjectSerializer.createSpecificInternal(ObjectSerializer.java:96)
        at io.micronaut.serde.support.serializers.ObjectSerializer.createSpecific(ObjectSerializer.java:89)
        at io.micronaut.serde.jackson.JacksonJsonMapper.writeValue(JacksonJsonMapper.java:108)
```

### To Reproduce:

https://github.com/micronaut-projects/micronaut-microstream/pull/186

- Check out the M3 branch of micronaut-microstream
- Run the failing Rest spec with:
    ```
    ./gradlew m-m-r:test --tests MicroStreamRestControllerSpec
    ```

**Comment by graemerocher** [comment]
likely fixed by https://github.com/micronaut-projects/micronaut-serialization/pull/447/commits/70cd005f6c5795fe95a280f06e9d9bcb293066fb
