### ISSUE TITLE
Error loading BeanIntrospection for type [class example.micronaut.TeamConfiguration]: Duplicate key

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-serialization#513]
Using KSP with Serde (and the latest Micronaut Core) in the `micronaut-configuration` guide fails with

```
Caused by: io.micronaut.serde.exceptions.SerdeException: Error loading BeanIntrospection for type [class example.micronaut.TeamConfiguration]: Duplicate key
	at io.micronaut.serde.support.serializers.ObjectSerializer$4.tryToFindSerializer(ObjectSerializer.java:218)
	at io.micronaut.serde.support.serializers.ObjectSerializer$RuntimeTypeSerializer.lambda$getSerializer$0(ObjectSerializer.java:280)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at io.micronaut.serde.support.serializers.ObjectSerializer$RuntimeTypeSerializer.getSerializer(ObjectSerializer.java:278)
	at io.micronaut.serde.support.serializers.ObjectSerializer$RuntimeTypeSerializer.serialize(ObjectSerializer.java:245)
	at io.micronaut.serde.jackson.JacksonJsonMapper.writeValue(JacksonJsonMapper.java:114)
	at io.micronaut.serde.jackson.JacksonJsonMapper.writeValue(JacksonJsonMapper.java:193)
	at io.micronaut.json.body.JsonMessageHandler.writeTo(JsonMessageHandler.java:134)
	... 60 common frames omitted
Caused by: io.micronaut.core.beans.exceptions.IntrospectionException: Error loading BeanIntrospection for type [class example.micronaut.TeamConfiguration]: Duplicate key
	at io.micronaut.core.beans.DefaultBeanIntrospector.findIntrospection(DefaultBeanIntrospector.java:104)
	at io.micronaut.serde.support.DefaultSerdeIntrospections.getSerializableIntrospection(DefaultSerdeIntrospections.java:77)
	at io.micronaut.serde.support.serializers.SerBean.<init>(SerBean.java:107)
	at io.micronaut.serde.support.serializers.ObjectSerializer.create(ObjectSerializer.java:202)
	at io.micronaut.serde.support.serializers.ObjectSerializer.lambda$getSerBean$0(ObjectSerializer.java:193)
	at io.micronaut.core.util.SupplierUtil$2.get(SupplierUtil.java:79)
	at io.micronaut.serde.support.serializers.ObjectSerializer.getSerBean(ObjectSerializer.java:194)
	at io.micronaut.serde.support.serializers.ObjectSerializer.createSpecificInternal(ObjectSerializer.java:93)
	at io.micronaut.serde.support.serializers.ObjectSerializer.createSpecific(ObjectSerializer.java:86)
	at io.micronaut.serde.jackson.JacksonJsonMapper.writeValue(JacksonJsonMapper.java:112)
	... 62 common frames omitted
Caused by: java.lang.IllegalArgumentException: Duplicate key
	at io.micronaut.core.util.StringIntMap.put(StringIntMap.java:74)
	at io.micronaut.inject.beans.AbstractInitializableBeanIntrospection.<init>(AbstractInitializableBeanIntrospection.java:97)
	at example.micronaut.$TeamConfiguration$Introspection.<init>(Unknown Source)
	at example.micronaut.$TeamConfiguration$IntrospectionRef.load(Unknown Source)
	at io.micronaut.core.beans.DefaultBeanIntrospector.lambda$findIntrospection$0(DefaultBeanIntrospector.java:95)
	at java.base/java.util.Optional.map(Optional.java:260)
	at io.micronaut.core.beans.DefaultBeanIntrospector.findIntrospection(DefaultBeanIntrospector.java:91)
	... 71 common frames omitted
```

### Steps to reproduce:

- Open the micronaut-guides module
- Check out the `sdelamo-patch-3` for micronaut-4
- Remove `"kotlinFeatures": ["kapt"]` from `guides/micronaut-configuration/metadata.json`
- Run `./gradlew clean micronautConfigurationBuild --no-build-cache`

### Expected behavior

All the tests should pass

### Actual behavior

The Kotlin/Gradle test fails (where we use KSP)

**Comment by timyates** [comment]
As another data-point, we see the same issue (duplicate key) in the micronaut-data-access-mybatis guide as well with Kotlin/KSP

We have an endpoint:

```
    @Get(value = "/list{?args*}") // <8>
    open fun list(@Valid args: ListingArguments): List<Genre> = genreRepository.findAll(args)
```

But when we call it with no arguments in the `testGenreCrudOperations`, the server throws a response:

```
{
   "_links":{
      "self":[
         {
            "href":"/genres/list?offset=0",
            "templated":false
         }
      ]
   },
   "_embedded":{
      "errors":[
         {
            "message":"Failed to convert argument [args] for value [null] due to: Error loading BeanIntrospection for type [class example.micronaut.ListingArguments]: Duplicate key",
            "path":"/args"
         }
      ]
   },
   "message":"Bad Request"
}
```

**Comment by graemerocher** [comment]
what is the command to build mybatis guide?

**Comment by timyates** [comment]
```
./gradlew micronautDataAccessMybatisBuild
```

**Comment by timyates** [comment]
Fixed the Mybatis guide by using ideomatic kotlin https://github.com/micronaut-projects/micronaut-guides/pull/1269/commits/579a5a72c9af1430a1dc49fe3fb1f608c47d4187
