### ISSUE TITLE
Serde 2.3.0 throw exception with deserialization objects with discriminator

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-serialization#649]
Exception:
```
Error decoding JSON stream for type [animal]: Unknown property [class] encountered during deserialization of type: Animal
io.micronaut.http.codec.CodecException: Error decoding JSON stream for type [animal]: Unknown property [class] encountered during deserialization of type: Animal
	at app//io.micronaut.json.body.JsonMessageHandler.decorateRead(JsonMessageHandler.java:92)
	at app//io.micronaut.json.body.JsonMessageHandler.read(JsonMessageHandler.java:106)
	at app//io.micronaut.http.netty.body.NettyJsonHandler.read(NettyJsonHandler.java:115)
	at app//io.micronaut.http.client.netty.FullNettyClientHttpResponse.convertByteBuf(FullNettyClientHttpResponse.java:225)
	at app//io.micronaut.http.client.netty.FullNettyClientHttpResponse.lambda$getBody$0(FullNettyClientHttpResponse.java:174)
	at java.base@17.0.9/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at app//io.micronaut.http.client.netty.FullNettyClientHttpResponse.getBody(FullNettyClientHttpResponse.java:169)
	at app//io.micronaut.http.client.netty.FullNettyClientHttpResponse.<init>(FullNettyClientHttpResponse.java:108)
	at app//io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.forwardResponseToPromise(DefaultHttpClient.java:2163)
	at app//io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.channelReadInstrumented(DefaultHttpClient.java:2140)
	at app//io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.channelReadInstrumented(DefaultHttpClient.java:2108)
	at app//io.micronaut.http.client.netty.SimpleChannelInboundHandlerInstrumented.channelRead0(SimpleChannelInboundHandlerInstrumented.java:46)
	at app//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at app//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at app//io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at app//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at app//io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at app//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at app//io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at app//io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at app//io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at app//io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at app//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at app//io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at app//io.micronaut.http.client.netty.ResettableReadTimeoutHandler$NextInterceptor.channelRead(ResettableReadTimeoutHandler.java:92)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at app//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at app//io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at app//io.micronaut.http.client.netty.ResettableReadTimeoutHandler.channelRead(ResettableReadTimeoutHandler.java:64)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at app//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at app//io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at app//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at app//io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at app//io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at app//io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at app//io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.9/java.lang.Thread.run(Thread.java:840)
Caused by: io.micronaut.serde.exceptions.SerdeException: Unknown property [class] encountered during deserialization of type: Animal
	at app//io.micronaut.serde.support.deserializers.SimpleObjectDeserializer.unknownProperty(SimpleObjectDeserializer.java:125)
	at app//io.micronaut.serde.support.deserializers.SimpleObjectDeserializer.deserializeInto(SimpleObjectDeserializer.java:102)
	at app//io.micronaut.serde.support.deserializers.SimpleObjectDeserializer.deserialize(SimpleObjectDeserializer.java:68)
	at app//io.micronaut.serde.support.deserializers.SubtypedPropertyObjectDeserializer.deserialize(SubtypedPropertyObjectDeserializer.java:66)
	at app//io.micronaut.serde.Deserializer.deserializeNullable(Deserializer.java:85)
	at app//io.micronaut.serde.jackson.JacksonJsonMapper.readValue0(JacksonJsonMapper.java:177)
	at app//io.micronaut.serde.jackson.JacksonJsonMapper.readValue(JacksonJsonMapper.java:169)
	at app//io.micronaut.serde.jackson.JacksonJsonMapper.readValue(JacksonJsonMapper.java:224)
	at app//io.micronaut.json.body.JsonMessageHandler.read(JsonMessageHandler.java:104)
	... 52 more
```

Animal class:
```java
@Serdeable
@JsonPropertyOrder({
    Animal.JSON_PROPERTY_PROPERTY_CLASS,
    Animal.JSON_PROPERTY_COLOR
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
@JsonIgnoreProperties(
        value = "class", // ignore manually set class, it will be automatically generated by Jackson during serialization
        allowSetters = true // allows the class to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "class", visible = true)
@JsonSubTypes({
    @JsonSubTypes.Type(value = Bird.class, name = "ave"),
    @JsonSubTypes.Type(value = Mammal.class, name = "mammalia"),
    @JsonSubTypes.Type(value = Reptile.class, name = "reptilia")
})
@Introspected
public class Animal {

    public static final String JSON_PROPERTY_PROPERTY_CLASS = "class";
    public static final String JSON_PROPERTY_COLOR = "color";

    @HardNullable
    @Schema(name = "class", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty(JSON_PROPERTY_PROPERTY_CLASS)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    protected String propertyClass;

    @HardNullable
    @Schema(name = "color", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty(JSON_PROPERTY_COLOR)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private ColorEnum color;

    /**
     * @return the propertyClass property value
     */
    public String getPropertyClass() {
        return propertyClass;
    }

    /**
     * @return the propertyClass property value wrapped in an optional
     */
    @JsonIgnore
    public Optional<String> getPropertyClassOptional() {
        return Optional.ofNullable(propertyClass);
    }

    /**
     * Set the propertyClass property value
     */
    public void setPropertyClass(String propertyClass) {
        this.propertyClass = propertyClass;
    }

    /**
     * Set propertyClass in a chainable fashion.
     *
     * @return The same instance of Animal for chaining.
     */
    public Animal propertyClass(String propertyClass) {
        this.propertyClass = propertyClass;
        return this;
    }

    /**
     * @return the color property value
     */
    public ColorEnum getColor() {
        return color;
    }

    /**
     * @return the color property value wrapped in an optional
     */
    @JsonIgnore
    public Optional<ColorEnum> getColorOptional() {
        return Optional.ofNullable(color);
    }

    /**
     * Set the color property value
     */
    public void setColor(ColorEnum color) {
        this.color = color;
    }

    /**
     * Set color in a chainable fashion.
     *
     * @return The same instance of Animal for chaining.
     */
    public Animal color(ColorEnum color) {
        this.color = color;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Animal animal = (Animal) o;
        return Objects.equals(propertyClass, animal.propertyClass) &&
            Objects.equals(color, animal.color);
    }

    @Override
    public int hashCode() {
        return Objects.hash(propertyClass, color);
    }

    @Override
    public String toString() {
        return "Animal("
            + "propertyClass: " + getPropertyClass() + ", "
            + "color: " + getColor()
            + ")";
    }
}
```

controller method:
```java
    /**
     * A method to send a model with discriminator in body
     *
     * @param animal (required)
     * @return Mono&lt;@Valid Animal&gt;
     */
    @Put("/sendModelWithDiscriminator")
    Mono<@Valid Animal> sendModelWithDiscriminator(
        @Body @NotNull @Valid Animal animal
    );
```

Full reproduce this problem, look to this PR: https://github.com/micronaut-projects/micronaut-openapi/pull/1274. Test `RequestBodyControllerSpec."test send model with discriminator child: #discriminatorName"` works fine with serde 2.2.x, but has exception with serde 2.3.0

### Version

4.1.11

**Comment by altro3** [comment]
@graemerocher @dstepanov hi! We have a problem in the serde 2.3.0

**Comment by dstepanov** [comment]
The error is correct, you shouldn’t have visible true if your model doesn’t consume the discriminator property

**Comment by altro3** [comment]
@dstepanov Yes, I understand, but this class has discriminator property:
```java
    @HardNullable
    @Schema(name = "class", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty(JSON_PROPERTY_PROPERTY_CLASS)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    protected String propertyClass;
```

**Comment by dstepanov** [comment]
I didn't notice, will check tomorrow

**Comment by altro3** [comment]
@dstepanov look like wrong processsing this annotation:
```java
@JsonIgnoreProperties(
        value = "class", // ignore manually set class, it will be automatically generated by Jackson during serialization
        allowSetters = true // allows the class to be set during deserialization
)
```

**Comment by altro3** [comment]
@dstepanov still doesn't work (teste with serder 2.3.2).

Simple test with serialization / deserialization with jackson databind. Same classes as in test before Animal, Bird, Mammal, Reptile:
```java
    public void process() {
        
        var mapper = JsonMapper.builder()
                .build();

        var bird = new Bird()
                .numWings(2)
                .beakLength(BigDecimal.valueOf(12, 1))
                .featherDescription("Large blue and white feathers")
                .color(ColorEnum.BLUE);

        var mammal = new Mammal(20.5f, "A typical Canadian beaver")
                .color(ColorEnum.BLUE);

        var reptile = new Reptile(0, true)
                .fangDescription("A pair of venomous fangs")
                .color(ColorEnum.BLUE);

        log.info("Bird: {}", bird);
        log.info("Mammal: {}", mammal);
        log.info("Reptile: {}", reptile);

        try {
            
            var birdStr = "";
            var mammalStr = "";
            var reptileStr = "";

            log.info("Bird json: {}", birdStr = mapper.writeValueAsString(bird));
            log.info("Mammal json: {}", mammalStr = mapper.writeValueAsString(mammal));
            log.info("Reptile json: {}", reptileStr = mapper.writeValueAsString(reptile));

            log.info("Bird deserialized: {}", mapper.readValue(birdStr, Bird.class));
            log.info("Mammal deserialized: {}", mapper.readValue(mammalStr, Mammal.class));
            log.info("Reptile deserialized: {}", mapper.readValue(reptileStr, Reptile.class));
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
    }
```

logs:
```
Bird: Bird(propertyClass: null, color: blue)
Mammal: Mammal(propertyClass: null, color: blue)
Reptile: Reptile(propertyClass: null, color: blue)

Bird json: {"class":"ave","numWings":2,"beakLength":1.2,"featherDescription":"Large blue and white feathers","color":"blue"}
Mammal json: {"class":"mammalia","weight":20.5,"description":"A typical Canadian beaver","color":"blue"}
Reptile json: {"class":"reptilia","numLegs":0,"fangs":true,"fangDescription":"A pair of venomous fangs","color":"blue"}

Bird deserialized: Bird(propertyClass: ave, color: blue)
Mammal deserialized: Mammal(propertyClass: mammalia, color: blue)
Reptile deserialized: Reptile(propertyClass: reptilia, color: blue)
```

As I wrote before, the problem with processing annotation `@JsonIgnoreProperties`

**Comment by dstepanov** [comment]
Sorry haven’t looked at it yet

**Comment by dstepanov** [comment]
Can not reproduce it https://github.com/micronaut-projects/micronaut-serialization/pull/656 Maybe you are using an older version of the annotation processor somehow
