### ISSUE TITLE
Duplicate key error during BeanIntrospection when JSON property is on super interfaces

### ISSUE THREAD

**Issue by KangoV** [micronaut-projects/micronaut-serialization#668]
### Expected Behavior

De/serialisation should complete normally

### Actual Behaviour

Throws exception:
```
Error loading BeanIntrospection for type [class io.kangov.stixj.common.objects.sco.DomainName]: Duplicate key
io.micronaut.core.beans.exceptions.IntrospectionException: Error loading BeanIntrospection for type [class io.kangov.stixj.common.objects.sco.DomainName]: Duplicate key
	at app//io.micronaut.core.beans.DefaultBeanIntrospector.findIntrospection(DefaultBeanIntrospector.java:104)
	at app//io.micronaut.serde.support.DefaultSerdeIntrospections.getSerializableIntrospection(DefaultSerdeIntrospections.java:86)
	at app//io.micronaut.serde.support.serializers.SerBean.<init>(SerBean.java:111)
	at app//io.micronaut.serde.support.serializers.ObjectSerializer.lambda$getSerializableBean$0(ObjectSerializer.java:115)
	at app//io.micronaut.core.util.SupplierUtil$2.get(SupplierUtil.java:79)
	at app//io.micronaut.serde.support.serializers.ObjectSerializer.getSerializableBean(ObjectSerializer.java:120)
	at app//io.micronaut.serde.support.serializers.ObjectSerializer.createSpecificInternal(ObjectSerializer.java:84)
	at app//io.micronaut.serde.support.serializers.ObjectSerializer.createSpecific(ObjectSerializer.java:76)
	at app//io.micronaut.serde.support.serializers.ObjectSerializer.createSpecific(ObjectSerializer.java:52)
	at app//io.micronaut.serde.jackson.JacksonJsonMapper.writeValue(JacksonJsonMapper.java:159)
	at app//io.micronaut.serde.jackson.JacksonJsonMapper.writeValue0(JacksonJsonMapper.java:152)
	at app//io.micronaut.serde.jackson.JacksonJsonMapper.writeValue0(JacksonJsonMapper.java:147)
	at app//io.micronaut.serde.jackson.JacksonJsonMapper.writeValueAsBytes(JacksonJsonMapper.java:248)
	at app//io.micronaut.serde.ObjectMapper.writeValueAsString(ObjectMapper.java:39)
	at app//io.kangov.stixj.common.ObjectTest.testObjectToString(ObjectTest.java:35)
	at java.base@17.0.2/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base@17.0.2/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base@17.0.2/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.IllegalArgumentException: Duplicate key
	at io.micronaut.core.util.StringIntMap.put(StringIntMap.java:74)
	at io.micronaut.inject.beans.AbstractInitializableBeanIntrospection$IntrospectionBuilderData.init(AbstractInitializableBeanIntrospection.java:591)
	at io.micronaut.inject.beans.AbstractInitializableBeanIntrospection$IntrospectionBuilderData.<init>(AbstractInitializableBeanIntrospection.java:558)
	at io.micronaut.inject.beans.AbstractInitializableBeanIntrospection.getBuilderData(AbstractInitializableBeanIntrospection.java:459)
	at io.micronaut.inject.beans.AbstractInitializableBeanIntrospection.<init>(AbstractInitializableBeanIntrospection.java:94)
	at io.kangov.stixj.common.objects.sco.$DomainName$Introspection.<init>(Unknown Source)
	at io.kangov.stixj.common.objects.sco.$DomainName$IntrospectionRef.load(Unknown Source)
	at io.micronaut.core.beans.DefaultBeanIntrospector.lambda$findIntrospection$0(DefaultBeanIntrospector.java:95)
	at java.base/java.util.Optional.map(Optional.java:260)
	at io.micronaut.core.beans.DefaultBeanIntrospector.findIntrospection(DefaultBeanIntrospector.java:91)
	... 17 more
```

### Steps To Reproduce

Given an "Id" interface which describes an Id:

```
public interface Id {
    @JsonProperty("id")
    @Value.Default
    default String getId() {
        var type = "name";
        return type + "--" + UUID.randomUUID().toString();
    }
}
```

And an interface which describes the immutable object to be created:

```
@Value.Immutable
@Value.Style(
    passAnnotations = { Serdeable.class },
    additionalJsonAnnotations = { JsonTypeName.class },
    optionalAcceptNullable = true,
    typeImmutable = "*",
    typeAbstract = "*Spec",
    depluralize = true,
    validationMethod = Value.Style.ValidationMethod.NONE,
    defaults = @Value.Immutable(copy = false)
)
@Serial.Version(1L)
@JsonTypeName("domain-name")
@JsonSerialize(as = DomainName.class)
@JsonDeserialize(builder = DomainName.Builder.class)
@JsonPropertyOrder({ "id", "type" })
@JsonInclude( value = NON_EMPTY, content= NON_EMPTY)
@Serdeable
public interface DomainNameSpec extends Id {
    @NotBlank
    @JsonProperty("value")
    String getValue();
}

And a test:

```
    @Test
    void testObjectToString() throws Exception {

        var object = DomainName.builder()
            .id("6c9a1180-994e-4082-9a11-80994e308253")
            .value("mydomain.com")
            .build();

        var str = objectMapper.writeValueAsString(object);
        assertThat(str).isNotNull();

    }
```

If the Id is moved to the DomainName interface and the extends removed, it works.

### Environment Information

JDK
```
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7-44)
OpenJDK 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)
```
OS: MacOS 14.0
immutables : 2.9.2
Micronaut serde : v2.4.0


### Example Application

_No response_

### Version

4.1.2

**Comment by KangoV** [comment]
This was a red herring. The actual problem is with overloaded builder methods. Introspection barfs as it assembled attribute names. I'll create a more accurate issue.
