### ISSUE TITLE
Micronaut 4.2.0 breaks deserialization when using custom deserializer

### ISSUE THREAD

**Issue by saw303** [micronaut-projects/micronaut-serialization#686]
### Expected Behavior

In Micronaut 4.2.0 the deserialisation of the following JSON object fails. This was working in previous 4.x versions.

```json
{
  "@type": "m",
  "type": "DEDUCTIBLE_STATIONARY",
  "value": "COD_SB_000",
  "externalName": "PRD_ZV_SP3_CTK_SB_SS3_V001",
  "exposable": true,
  "typedValue": {
    "currency": "CHF",
    "amount": 0
  }
}
```

The error is 

```
Expected no exception to be thrown, but got 'java.lang.IllegalStateException'
	at spock.lang.Specification.noExceptionThrown(Specification.java:118)
	at ch.onstructive.salessystem.JacksonFFSSpec.Test(JacksonFFSSpec.groovy:45)
Caused by: java.lang.IllegalStateException: Entry already consumed
	at io.micronaut.serde.support.deserializers.DemuxingObjectDecoder$DemuxerState$Entry.provideDecoder(DemuxingObjectDecoder.java:229)
	at io.micronaut.serde.support.deserializers.DemuxingObjectDecoder$DemuxerState$Entry.peekOrConsume(DemuxingObjectDecoder.java:211)
	at io.micronaut.serde.support.deserializers.DemuxingObjectDecoder.delegate(DemuxingObjectDecoder.java:110)
	at io.micronaut.serde.DelegatingDecoder.decodeString(DelegatingDecoder.java:79)
	at ch.onstructive.micronaut.serde.MonetaryAmountSerde.deserialize(MonetaryAmountSerde.java:48)
	at ch.onstructive.micronaut.serde.MonetaryAmountSerde.deserialize(MonetaryAmountSerde.java:29)
	at io.micronaut.serde.Deserializer.deserializeNullable(Deserializer.java:85)
	at io.micronaut.serde.support.deserializers.SpecificObjectDeserializer.deserializeValue(SpecificObjectDeserializer.java:193)
```

### Actual Behaviour

Deserialisation should work

### Steps To Reproduce

1. Clone https://github.com/saw303/micronaut420-serde-issue
2. Checkout branch `4.2.0-fails`
3. Run `./gradlew check`

The test will fail.

Same test runs with Micronaut 4.1.6 on branch `4.1.6-works`

### Example Application

https://github.com/saw303/micronaut420-serde-issue

### Version

4.2.0

**Comment by yawkat** [comment]
Your serde is buggy, it uses the wrong decoder to decode the fields. This change fixes it:

```patch
Index: src/main/java/io/wangler/micronaut/MonetaryAmountSerde.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/java/io/wangler/micronaut/MonetaryAmountSerde.java b/src/main/java/io/wangler/micronaut/MonetaryAmountSerde.java
--- a/src/main/java/io/wangler/micronaut/MonetaryAmountSerde.java	(revision 26b822e6774e34b4caa08a028630745ec4cbbb4f)
+++ b/src/main/java/io/wangler/micronaut/MonetaryAmountSerde.java	(date 1700576746739)
@@ -46,9 +46,9 @@
       while (key != null) {
 
         if (Objects.equals("currency", key)) {
-          currency = decoder.decodeString();
+          currency = decoder1.decodeString();
         } else if (Objects.equals("amount", key)) {
-          amount = decoder.decodeBigDecimal();
+          amount = decoder1.decodeBigDecimal();
         }
         key = decoder1.decodeKey();
       }
```

**Comment by saw303** [comment]
🤦🏼‍♂️ Thank you so much for pointing this out. I did not analyse my code properly, since it was «working» in previous versions. Sorry, for this false alarm.

**Comment by yawkat** [comment]
yea sometimes we return the same decoder for decodeObject as an optimization but unfortunately it lets invalid calls like this through.
