### ISSUE TITLE
Micronaut proxy class throws `java.lang.ClassCastException` in deserialization

### ISSUE THREAD

**Issue by rost5000** [micronaut-projects/micronaut-serialization#689]
### Expected Behavior

Normal serialization and deserialization with Jackson annotations. It seems to me that Micronaut serialization produces the wrong proxy classes when I use `@JsonTypeInfo` and inheritance. 

Micronaut tried to call the wrong setter when deserialization occurred in my example: https://github.com/rost5000/micronaut-serialization-bug.git

### Actual Behaviour

I expect to see the correct proxy class generation with correct calling setters in deserialization.

### Steps To Reproduce

1. Graalvm 21 (Oracle Corporation 21+35-jvmci-23.1-b15) (tested in Windows machine)
2. clone the project: https://github.com/rost5000/micronaut-serialization-bug.git
3. Run `./gradlew clean build`
4. You can see the exception in test launching:
```text
io.micronaut.serde.exceptions.SerdeException: Error decoding property [Request request] of type [class com.example2.dtos.RequestWrapper]: class com.example2.dtos.commons.OutputSettings cannot be cast to class java.lang.String (com.example2.dtos.commons.OutputSettings is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	at app//io.micronaut.serde.support.deserializers.DeserBean$DerProperty.deserializeAndSetConstructorValue(DeserBean.java:857)
	at app//io.micronaut.serde.support.deserializers.SimpleRecordLikeObjectDeserializer.deserialize(SimpleRecordLikeObjectDeserializer.java:68)
	at app//io.micronaut.serde.support.deserializers.SimpleRecordLikeObjectDeserializer.deserializeNullable(SimpleRecordLikeObjectDeserializer.java:102)
	at app//io.micronaut.serde.jackson.JacksonJsonMapper.readValue0(JacksonJsonMapper.java:177)
	at app//io.micronaut.serde.jackson.JacksonJsonMapper.readValue(JacksonJsonMapper.java:169)
	at app//io.micronaut.serde.jackson.JacksonJsonMapper.readValue(JacksonJsonMapper.java:215)
	at app//io.micronaut.json.JsonMapper.readValue(JsonMapper.java:141)
	at app//io.micronaut.json.JsonMapper.readValue(JsonMapper.java:168)
	at app//com.example.MicronautSerializerJsonTypeInfoTest.doTest1(MicronautSerializerJsonTypeInfoTest.java:45)
	at java.base@21/java.lang.reflect.Method.invoke(Method.java:580)
	at app//io.micronaut.test.extensions.junit5.MicronautJunit5Extension$2.proceed(MicronautJunit5Extension.java:142)
	at app//io.micronaut.test.extensions.AbstractMicronautExtension.interceptEach(AbstractMicronautExtension.java:157)
	at app//io.micronaut.test.extensions.AbstractMicronautExtension.interceptTest(AbstractMicronautExtension.java:114)
	at app//io.micronaut.test.extensions.junit5.MicronautJunit5Extension.interceptTestMethod(MicronautJunit5Extension.java:129)
	at java.base@21/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base@21/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ClassCastException: class com.example2.dtos.commons.OutputSettings cannot be cast to class java.lang.String (com.example2.dtos.commons.OutputSettings is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	at com.example.config.$com_example2_dtos_RequestType1$Introspection.dispatchOne(Unknown Source)
	at io.micronaut.inject.beans.AbstractInitializableBeanIntrospection$BeanPropertyImpl.setUnsafe(AbstractInitializableBeanIntrospection.java:877)
	at io.micronaut.serde.support.deserializers.DeserBean$DerProperty.set(DeserBean.java:832)
	at io.micronaut.serde.support.deserializers.SpecificObjectDeserializer$CachedPropertiesValuesDeserializer.injectProperties(SpecificObjectDeserializer.java:343)
	at io.micronaut.serde.support.deserializers.SpecificObjectDeserializer$ArgsConstructorBeanDeserializer.provideInstance(SpecificObjectDeserializer.java:773)
	at io.micronaut.serde.support.deserializers.SpecificObjectDeserializer.deserialize(SpecificObjectDeserializer.java:102)
	at io.micronaut.serde.support.deserializers.SpecificObjectDeserializer.deserialize(SpecificObjectDeserializer.java:66)
	at io.micronaut.serde.support.deserializers.SubtypedPropertyObjectDeserializer.deserialize(SubtypedPropertyObjectDeserializer.java:66)
	at io.micronaut.serde.Deserializer.deserializeNullable(Deserializer.java:85)
	at io.micronaut.serde.support.deserializers.DeserBean$DerProperty.deserializeAndSetConstructorValue(DeserBean.java:838)
	... 15 more
```

### Environment Information

- Windows
- GraalVm 21 (Oracle Corporation 21+35-jvmci-23.1-b15)

### Example Application

https://github.com/rost5000/micronaut-serialization-bug.git

### Version

4.2.0

**Comment by rost5000** [comment]
Small hint: if you declare a constructor for all parameters, the problem will be solved, however, it seems to me that it is workaround
